### ISSUE TITLE
[BUG] Nether ores in overworld (Terralith)

### ISSUE THREAD

**Issue by arzadu** [lukebemish/excavated_variants#103]
### What went wrong?

When using Excavated Variants with Terralith (v2.2.2) and mods that add ores to the nether (in this case, Gobber v2.6.37), the nether ores will sometimes generate in the overworld blackstone generated by Terralith. I'm not sure if this is happening because of my configs or something else, so I've attached my config setup below.
Config folder: [excavated_variants.zip](https://github.com/lukebemish/excavated_variants/files/9990833/excavated_variants.zip)
Config file: [excavated_variants.json.zip](https://github.com/lukebemish/excavated_variants/files/9990839/excavated_variants.json.zip)

### Platform

Forge

### Version

0.6.4

**Comment by lukebemish** [comment]
You could try setting `attempt_ore_generation_insertion` to false, I suppose; this issue seems like it would have to be at least partially on gobber's side, since I don't do anything unless the ore placement feature is already there; basically, gobber is trying to generate its ores everywhere, and only failing because there's normally no netherrack except in the nether. Turning that setting to false will rely on ore replacement instead of the insertion, which is generally about as good. Regardless, the 1.18.2 version is out of active development, so I can try to offer input but won't be changing anything on my end.

**Comment by arzadu** [comment]
Thanks for the advice! I'll look into both of those when I get a chance.
