### ISSUE TITLE
[BUG] Issue with mineable/pickaxe tag

### ISSUE THREAD

**Issue by ma-gician** [lukebemish/excavated_variants#155]
### What went wrong?

Removed the ability to mine anything with a pickaxe.

### Platform

Forge

### Version

0.6.5 (MC 1.18.2)

### Logs and Screenshots

log: https://mclo.gs/Rhr8hj5

**Comment by lukebemish** [comment]
Try disabling nitre ore. For some reason it is attempting to set it up even though the underlying block does not exist, which probably means there's a config which needs changed

**Comment by ma-gician** [comment]
I misspelled niter. That was the issue. If this is a non bug, why won't my kubejs ore have it's texture appear on the other stone types? 
![image](https://github.com/lukebemish/ExcavatedVariants/assets/127440103/17087694-2491-40fb-8908-8e7807a673cb)
![image](https://github.com/lukebemish/ExcavatedVariants/assets/127440103/0c46e663-23f8-419e-a734-4c103b842dca)

**Comment by lukebemish** [comment]
That's because the way KubeJS provides textures is... Unconventional, and for some reason they chose not to use a lot of the built in systems so it's difficult for me to pick out their textures. I think the changes I made in newer versions improved that, and KubeJS may have improved it on their end too, but there's nothing to be done about that in 1.18.2 except providing the textures through a more "conventional" source - resource packs or mods, generally, though there may be mods out there for global resources
