### ISSUE TITLE
Minecraft starts to launch, but crashes!

### ISSUE THREAD

**Issue by Feliks-WR** [lukebemish/excavated_variants#170]
### What went wrong?

Check the log below

### Platform

Quilt

### Version

3.0.8

### Logs and Screenshots

[2023-09-26-3.log](https://github.com/lukebemish/ExcavatedVariants/files/12727161/2023-09-26-3.log)

**Comment by lukebemish** [comment]
Try removing `apoli`; I see a mixin error from it in that log. I'm seeing... nothing that seems to implicate Excavated Variants as part of the issue, so if there's more information there that relates to Excavated Variants you need to share it because I can't see it in the log. Closing for now but I'll re-open if there's more information
