### ISSUE TITLE
[Feature] Support for modded ores

### ISSUE THREAD

**Issue by vizthex123** [lukebemish/excavated_variants#203]
Mainly for Thermal Expansion, but it'd be nice if the mod work with all modded ores.

I know there was a mod like this for old versions that did that, but I can't remember its name...

**Comment by lukebemish** [comment]
This mod _does_ work with all modded ores. You just have to add a config file for the mod in question - there's no way to reliably detect what blocks are an "ore" block and what sorts of stone they should go in otherwise. The format is documented on the README; default configs are already set up for many mods, though some may not be up to date.

**Comment by vizthex123** [comment]
Didn't know it could be configured lol, but I'll check it out.

Could you add a link to the README in the wiki field on the CurseForge page? Would make it much easier to find.
