### ISSUE TITLE
[ENHANCEMENT] Add Support for Mekanism

### ISSUE THREAD

**Issue by Peach774** [lukebemish/excavated_variants#23]
### What feature would improve this mod?

Mekanism has been released for 1.18.2, support should be added for that mod's ores.

### Why would this feature be useful?

It would allow the ores from Mekanism to work with this mod.

### Mod Compatibility

- [X] This feature cannot be added through the config

**Comment by lukebemish** [comment]
Did you *read* the text by the check box before clicking it? This can almost certainly be added through a default config; feel free to write the config and open a pull request to add it. Otherwise, please give more info about *why* this cannot be done with a  config, and what new feature is actually needed.
