### ISSUE TITLE
[REQUEST] Automatic translate

### ISSUE THREAD

**Issue by lzm11111111** [lukebemish/excavated_variants#235]
The ore doesn't support languages other than English please make it

**Comment by lukebemish** [comment]
The mod totally supports translations in its data format, folks just need to either provide those themselves by configuring it, or PR them to this repo. There's no sane way to _automatically_ produce translations, though -- all I have is a translated name of the stone and a translated name of the ore; there's no way of combining those that'll work in all cases for all languages.

**Comment by lukebemish** [comment]
Closing this issue as the feature already exists -- the data format has a translation map in it. I provide `en_us` translations myself because that's what I speak, and I'm not confident with any other languages to provide translations, so anything else is up to other folks to set up or contribute -- the format already fully supports that though.
