### ISSUE TITLE
[ENHANCEMENT] Recipe duplicates

### ISSUE THREAD

**Issue by StockiesLad** [lukebemish/excavated_variants#61]
### What feature would improve this mod?

lets say that minecraft:gold_ore has a recipe where it can be crushed into dust with the create mod. If Excavated variants add more variants, instead of having to manually apply kubejs to thousands of blocks, excavated variants could do this at runtime,

### Why would this feature be useful?

It would save literal weeks of work as well as having out-of-the-box mod compat.

### Mod Compatibility

- [X] This feature cannot be added through the config

**Comment by lukebemish** [comment]
This feature is *already implemented* so long as mods do the correct thing and use tags in their recipes. All added ores are in the proper tags.

**Comment by StockiesLad** [comment]
oh I didn't know that

**Comment by goldenapple3** [comment]
@lukebemish The problem is that Minecraft itself does not use common tags in its recipes, so you can't even smelt Excavated Variants iron ore into ingots, it specifically expects Iron Ore or Deepslate Iron Ore.

@FluffyBumblebees the reason why Create crushing recipes don't use tags is because one of the byproducts is Cobblestone for regular ores, Deepslate for deepslate ores, etc., so it has to use specific item IDs.

**Comment by lukebemish** [comment]
Minecraft has a built in iron ore tag; if they fail to use it, that's on them, and it's all of two recipes for you to add anyways

**Comment by lukebemish** [comment]
In the same line of thought, if create fails to expect modded ores, that's their issue.
